# version: '3'
services:
  auth-service:
    build: ./auth-service
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/authservice

  product-service:
    build: ./product-service
    ports:
      - "8001:8001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/productservice

  order-service:
    build: ./order-service
    ports:
      - "8002:8002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/orderservice

  payment-service:
    build: ./payment-service
    ports:
      - "8003:8003"
    environment:
      - MONGO_URI=mongodb://mongo:27017/paymentservice

  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"
    depends_on:
      - auth-service
      - product-service
      - order-service
      - payment-service

  mongo:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - ./data:/data/db
